app/models.py
class User:
    pass

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_redis import FlaskRedis


from config import config

bootstrap = Bootstrap()
moment = Moment()
db = SQLAlchemy()
redis = FlaskRedis()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    redis.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .camera import camera as camera_blueprint
    app.register_blueprint(camera_blueprint)

    from .car import car as car_blueprint
    app.register_blueprint(car_blueprint)

    return app

app/camera/__init__.py
from flask import Blueprint

camera = Blueprint('camera', __name__)
from . import views

app/camera/views.py
from flask import Response, render_template

# from .camera_test import Camera
from .camera_pi import Camera
# from .camera_opencv import Camera

from app.camera import camera


@camera.route('/camera/')
def index():
    return render_template("camera/index.html")


def gen(camera):
    """Video streaming generator function."""
    while True:
        frame = camera.get_frame()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')


@camera.route('/camera/video_feed')
def video_feed():
    """Video streaming route. Put this in the src attribute of an img tag."""
    return Response(gen(Camera()),
                    mimetype='multipart/x-mixed-replace; boundary=frame')

app/car/__init__.py
from flask import Blueprint

car = Blueprint('car', __name__)
from . import views

app/car/views.py
#  -*- coding: utf-8 -*-

from flask import render_template, Response, redirect, url_for

from app import redis
from app.car import car
from app.main import main


@car.route('/car/')
def index():
    return render_template('car/index.html')


@car.route('/car/control/<string:direction>/')
def control(direction):
    redis.publish("direction", direction)
    return ""

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)
from . import views, errors

app/main/views.py
from flask import request, render_template, Response, redirect, url_for
import psutil, json

from app.main import main


@main.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        temp = 0
        with open('/sys/class/thermal/thermal_zone0/temp') as f:
            temp = float(f.read()) / 1000.0
        data = {
            'mem': psutil.virtual_memory().percent,
            'cpu': psutil.cpu_percent(interval=None, percpu=False),
            'net': round(temp, 1)
        }
        return json.dumps(data)
    return render_template('index.html')

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}{% endblock %}

{% block head %}
    {{ super() }}
    {#<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">#}
    {#<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">#}
{% endblock %}

{% block navbar %}
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle"
                        data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Test</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Home</a></li>
                </ul>
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('car.index') }}">Car</a></li>
                </ul>
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('camera.index') }}">Camera</a></li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        {% block page_content %}{% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='echarts.min.js') }}"></script>
{% endblock %}

app/templates/camera/index.html
{% extends "base.html" %}

{% block title %}摄像头{% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block page_content %}
    <div align="center">
        <h2 id="direction" align="center">摄像头界面</h2>
        <img src="{{ url_for('camera.video_feed') }}">
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
{% endblock %}

app/templates/car/index.html
{% extends "base.html" %}

{% block title %}小车控制{% endblock %}
{% block head %}
{{ super() }}
<style>
button{
    width: 100px;
    height:40px;
}
</style>
{% endblock %}
{% block page_content %}
    <div align="center">
        <h3 id="direction" align="center">STOP</h3>
        <img src="{{ url_for('camera.video_feed') }}">
    </div>
    <div align="center">
        <div>
            <button id="foreward"> Foreward</button>
        </div>
        <div>
            <button id="left"> Left</button>

            <button id="right"> Right</button>
        </div>
        <div>
            <button id="backward"> Backward</button>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $(function () {
            $("#foreward").mousedown(function () {
                $.get("{{ url_for("car.control", direction="foreward") }}");
                $("#direction").html("FOREWARD");
            });
            $("#left").mousedown(function () {
                $.get("{{ url_for("car.control", direction="left") }}");
                $("#direction").html("LEFT");
            });
            $("#right").mousedown(function () {
                $.get("{{ url_for("car.control", direction="right") }}");
                $("#direction").html("RIGHT");
            });
            $("#backward").mousedown(function () {
                $.get("{{ url_for("car.control", direction="backward") }}");
                $("#direction").html("BACKWARD");
            });
            $("button").mouseup(function () {
                $.get("{{ url_for("car.control", direction="stop") }}");
                $("#direction").html("STOP");
            });
        })
    </script>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}总览{% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block page_content %}
    <div id="main" style="width: 800px;height:600px;"></div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $(function () {
            // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('main'));

        // 指定图表的配置项和数据
        var option = {
            tooltip : {
                formatter: "{a} <br/>{c} {b}"
            },
            toolbox: {
                show: true,
                feature: {
                    restore: {show: true},
                    saveAsImage: {show: true}
                }
            },
            series : [
                {
                    name: 'CPU',
                    type: 'gauge',
                    z: 3,
                    min: 0,
                    max: 100,
                    splitNumber: 10,
                    radius: '50%',
                    axisLine: {            // 坐标轴线
                        lineStyle: {       // 属性lineStyle控制线条样式
                            width: 10
                        }
                    },
                    axisTick: {            // 坐标轴小标记
                        length: 15,        // 属性length控制线长
                        lineStyle: {       // 属性lineStyle控制线条样式
                            color: 'auto'
                        }
                    },
                    splitLine: {           // 分隔线
                        length: 20,         // 属性length控制线长
                        lineStyle: {       // 属性lineStyle（详见lineStyle）控制线条样式
                            color: 'auto'
                        }
                    },
                    axisLabel: {
                        backgroundColor: 'auto',
                        borderRadius: 2,
                        color: '#eee',
                        padding: 3,
                        textShadowBlur: 2,
                        textShadowOffsetX: 1,
                        textShadowOffsetY: 1,
                        textShadowColor: '#222'
                    },
                    title : {
                        // 其余属性默认使用全局文本样式，详见TEXTSTYLE
                        fontWeight: 'bolder',
                        fontSize: 20,
                        fontStyle: 'italic'
                    },
                    detail : {
                        // 其余属性默认使用全局文本样式，详见TEXTSTYLE
                        formatter: function (value) {
                            value = (value + '').split('.');
                            value.length < 2 && (value.push('00'));
                            return ('00' + value[0]).slice(-2)
                                + '.' + (value[1] + '00').slice(0, 2);
                        },
                        fontWeight: 'bolder',
                        borderRadius: 3,
                        backgroundColor: '#444',
                        borderColor: '#aaa',
                        shadowBlur: 5,
                        shadowColor: '#333',
                        shadowOffsetX: 0,
                        shadowOffsetY: 3,
                        borderWidth: 2,
                        textBorderColor: '#000',
                        textBorderWidth: 2,
                        textShadowBlur: 2,
                        textShadowColor: '#fff',
                        textShadowOffsetX: 0,
                        textShadowOffsetY: 0,
                        fontFamily: 'Arial',
                        width: 100,
                        color: '#eee',
                        rich: {}
                    },
                    data:[{value: 40, name: 'CPU'}]
                },
                {
                    name: 'MEM',
                    type: 'gauge',
                    center: ['20%', '55%'],    // 默认全局居中
                    radius: '35%',
                    min:0,
                    max:100,
                    endAngle:45,
                    splitNumber:10,
                    axisLine: {            // 坐标轴线
                        lineStyle: {       // 属性lineStyle控制线条样式
                            width: 8
                        }
                    },
                    axisTick: {            // 坐标轴小标记
                        length:12,        // 属性length控制线长
                        lineStyle: {       // 属性lineStyle控制线条样式
                            color: 'auto'
                        }
                    },
                    splitLine: {           // 分隔线
                        length:20,         // 属性length控制线长
                        lineStyle: {       // 属性lineStyle（详见lineStyle）控制线条样式
                            color: 'auto'
                        }
                    },
                    pointer: {
                        width:5
                    },
                    title: {
                        offsetCenter: [0, '-30%']      // x, y，单位px
                    },
                    detail: {
                        // 其余属性默认使用全局文本样式，详见TEXTSTYLE
                        fontWeight: 'bolder'
                    },
                    data:[{value: 1.5, name: 'MEM'}]
                },
                {
                    name: 'TEMP',
                    type: 'gauge',
                    center: ['77%', '55%'],    // 默认全局居中
                    radius: '35%',
                    min:0,
                    max:100,
                    startAngle:125,
                    splitNumber:10,
                    axisLine: {            // 坐标轴线
                        lineStyle: {       // 属性lineStyle控制线条样式
                            width: 8
                        }
                    },
                    axisTick: {            // 坐标轴小标记
                        length:12,        // 属性length控制线长
                        lineStyle: {       // 属性lineStyle控制线条样式
                            color: 'auto'
                        }
                    },
                    splitLine: {           // 分隔线
                        length:20,         // 属性length控制线长
                        lineStyle: {       // 属性lineStyle（详见lineStyle）控制线条样式
                            color: 'auto'
                        }
                    },
                    pointer: {
                        width:5
                    },
                    title: {
                        offsetCenter: [0, '-30%']      // x, y，单位px
                    },
                    detail: {
                        // 其余属性默认使用全局文本样式，详见TEXTSTYLE
                        fontWeight: 'bolder'
                    },
                    data:[{value: 1.5, name: 'TEMP'}]
                }
            ]
        };

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);

        setInterval(function () {
            $.ajax({
                type: 'POST',
                data: [],
                url: "{{ url_for('main.index') }}",
                dataType: "json",
                success: function (result) {
                    option.series[0].data[0].value = result.cpu;
                    option.series[1].data[0].value = result.mem;
                    option.series[2].data[0].value = result.net;
                    myChart.setOption(option, true);
                }
            });
        }, 1000);
        })
    </script>
{% endblock %}

templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}{% endblock %}

{% block head %}
    {{ super() }}
    {#<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">#}
    {#<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">#}
{% endblock %}

{% block navbar %}
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle"
                        data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Test</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Home</a></li>
                </ul>
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('car.index') }}">Car</a></li>
                </ul>
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('camera.index') }}">Camera</a></li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        {% block page_content %}{% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='echarts.min.js') }}"></script>
{% endblock %}

templates/camera/index.html
{% extends "base.html" %}

{% block title %}摄像头{% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block page_content %}
    <div align="center">
        <h2 id="direction" align="center">摄像头界面</h2>
        <img src="{{ url_for('camera.video_feed') }}">
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
{% endblock %}

templates/car/index.html
{% extends "base.html" %}

{% block title %}小车控制{% endblock %}
{% block head %}
{{ super() }}
<style>
button{
    width: 100px;
    height:40px;
}
</style>
{% endblock %}
{% block page_content %}
    <div align="center">
        <h3 id="direction" align="center">STOP</h3>
        <img src="{{ url_for('camera.video_feed') }}">
    </div>
    <div align="center">
        <div>
            <button id="foreward"> Foreward</button>
        </div>
        <div>
            <button id="left"> Left</button>

            <button id="right"> Right</button>
        </div>
        <div>
            <button id="backward"> Backward</button>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $(function () {
            $("#foreward").mousedown(function () {
                $.get("{{ url_for("car.control", direction="foreward") }}");
                $("#direction").html("FOREWARD");
            });
            $("#left").mousedown(function () {
                $.get("{{ url_for("car.control", direction="left") }}");
                $("#direction").html("LEFT");
            });
            $("#right").mousedown(function () {
                $.get("{{ url_for("car.control", direction="right") }}");
                $("#direction").html("RIGHT");
            });
            $("#backward").mousedown(function () {
                $.get("{{ url_for("car.control", direction="backward") }}");
                $("#direction").html("BACKWARD");
            });
            $("button").mouseup(function () {
                $.get("{{ url_for("car.control", direction="stop") }}");
                $("#direction").html("STOP");
            });
        })
    </script>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}总览{% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block page_content %}
    <div id="main" style="width: 800px;height:600px;"></div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $(function () {
            // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('main'));

        // 指定图表的配置项和数据
        var option = {
            tooltip : {
                formatter: "{a} <br/>{c} {b}"
            },
            toolbox: {
                show: true,
                feature: {
                    restore: {show: true},
                    saveAsImage: {show: true}
                }
            },
            series : [
                {
                    name: 'CPU',
                    type: 'gauge',
                    z: 3,
                    min: 0,
                    max: 100,
                    splitNumber: 10,
                    radius: '50%',
                    axisLine: {            // 坐标轴线
                        lineStyle: {       // 属性lineStyle控制线条样式
                            width: 10
                        }
                    },
                    axisTick: {            // 坐标轴小标记
                        length: 15,        // 属性length控制线长
                        lineStyle: {       // 属性lineStyle控制线条样式
                            color: 'auto'
                        }
                    },
                    splitLine: {           // 分隔线
                        length: 20,         // 属性length控制线长
                        lineStyle: {       // 属性lineStyle（详见lineStyle）控制线条样式
                            color: 'auto'
                        }
                    },
                    axisLabel: {
                        backgroundColor: 'auto',
                        borderRadius: 2,
                        color: '#eee',
                        padding: 3,
                        textShadowBlur: 2,
                        textShadowOffsetX: 1,
                        textShadowOffsetY: 1,
                        textShadowColor: '#222'
                    },
                    title : {
                        // 其余属性默认使用全局文本样式，详见TEXTSTYLE
                        fontWeight: 'bolder',
                        fontSize: 20,
                        fontStyle: 'italic'
                    },
                    detail : {
                        // 其余属性默认使用全局文本样式，详见TEXTSTYLE
                        formatter: function (value) {
                            value = (value + '').split('.');
                            value.length < 2 && (value.push('00'));
                            return ('00' + value[0]).slice(-2)
                                + '.' + (value[1] + '00').slice(0, 2);
                        },
                        fontWeight: 'bolder',
                        borderRadius: 3,
                        backgroundColor: '#444',
                        borderColor: '#aaa',
                        shadowBlur: 5,
                        shadowColor: '#333',
                        shadowOffsetX: 0,
                        shadowOffsetY: 3,
                        borderWidth: 2,
                        textBorderColor: '#000',
                        textBorderWidth: 2,
                        textShadowBlur: 2,
                        textShadowColor: '#fff',
                        textShadowOffsetX: 0,
                        textShadowOffsetY: 0,
                        fontFamily: 'Arial',
                        width: 100,
                        color: '#eee',
                        rich: {}
                    },
                    data:[{value: 40, name: 'CPU'}]
                },
                {
                    name: 'MEM',
                    type: 'gauge',
                    center: ['20%', '55%'],    // 默认全局居中
                    radius: '35%',
                    min:0,
                    max:100,
                    endAngle:45,
                    splitNumber:10,
                    axisLine: {            // 坐标轴线
                        lineStyle: {       // 属性lineStyle控制线条样式
                            width: 8
                        }
                    },
                    axisTick: {            // 坐标轴小标记
                        length:12,        // 属性length控制线长
                        lineStyle: {       // 属性lineStyle控制线条样式
                            color: 'auto'
                        }
                    },
                    splitLine: {           // 分隔线
                        length:20,         // 属性length控制线长
                        lineStyle: {       // 属性lineStyle（详见lineStyle）控制线条样式
                            color: 'auto'
                        }
                    },
                    pointer: {
                        width:5
                    },
                    title: {
                        offsetCenter: [0, '-30%']      // x, y，单位px
                    },
                    detail: {
                        // 其余属性默认使用全局文本样式，详见TEXTSTYLE
                        fontWeight: 'bolder'
                    },
                    data:[{value: 1.5, name: 'MEM'}]
                },
                {
                    name: 'NET',
                    type: 'gauge',
                    center: ['77%', '55%'],    // 默认全局居中
                    radius: '35%',
                    min:0,
                    max:100,
                    startAngle:125,
                    splitNumber:10,
                    axisLine: {            // 坐标轴线
                        lineStyle: {       // 属性lineStyle控制线条样式
                            width: 8
                        }
                    },
                    axisTick: {            // 坐标轴小标记
                        length:12,        // 属性length控制线长
                        lineStyle: {       // 属性lineStyle控制线条样式
                            color: 'auto'
                        }
                    },
                    splitLine: {           // 分隔线
                        length:20,         // 属性length控制线长
                        lineStyle: {       // 属性lineStyle（详见lineStyle）控制线条样式
                            color: 'auto'
                        }
                    },
                    pointer: {
                        width:5
                    },
                    title: {
                        offsetCenter: [0, '-30%']      // x, y，单位px
                    },
                    detail: {
                        // 其余属性默认使用全局文本样式，详见TEXTSTYLE
                        fontWeight: 'bolder'
                    },
                    data:[{value: 1.5, name: 'NET'}]
                }
            ]
        };

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);

        setInterval(function () {
            $.ajax({
                type: 'POST',
                data: [],
                url: "{{ url_for('main.index') }}",
                dataType: "json",
                success: function (result) {
                    option.series[0].data[0].value = result.cpu;
                    option.series[1].data[0].value = result.mem;
                    option.series[2].data[0].value = result.net;
                    myChart.setOption(option, true);
                }
            });
        }, 1000);
        })
    </script>
{% endblock %}